/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class framework_Manager_VideoManager */

#ifndef _Included_framework_Manager_VideoManager
#define _Included_framework_Manager_VideoManager
#ifdef __cplusplus
extern "C" {
#endif
#undef framework_Manager_VideoManager_MIN_PRIORITY
#define framework_Manager_VideoManager_MIN_PRIORITY 1L
#undef framework_Manager_VideoManager_NORM_PRIORITY
#define framework_Manager_VideoManager_NORM_PRIORITY 5L
#undef framework_Manager_VideoManager_MAX_PRIORITY
#define framework_Manager_VideoManager_MAX_PRIORITY 10L
#undef framework_Manager_VideoManager_BIT_RATE
#define framework_Manager_VideoManager_BIT_RATE 2000000L
#undef framework_Manager_VideoManager_FRAME_RATE
#define framework_Manager_VideoManager_FRAME_RATE 30L
#undef framework_Manager_VideoManager_IFRAME_INTERVAL
#define framework_Manager_VideoManager_IFRAME_INTERVAL 10L
/*
 * Class:     framework_Manager_VideoManager
 * Method:    YUVtoBytes
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIIIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_framework_Manager_VideoManager_YUVtoBytes
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
