/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class framework_Thread_InferenceThread_Callback */

#ifndef _Included_framework_Thread_InferenceThread_Callback
#define _Included_framework_Thread_InferenceThread_Callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
