/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class framework_Thread_InferenceThread */

#ifndef _Included_framework_Thread_InferenceThread
#define _Included_framework_Thread_InferenceThread
#ifdef __cplusplus
extern "C" {
#endif
#undef framework_Thread_InferenceThread_MINIMUM_CONFIDENCE
#define framework_Thread_InferenceThread_MINIMUM_CONFIDENCE 0.5f
/*
 * Class:     framework_Thread_InferenceThread
 * Method:    YUVtoRGB
 * Signature: ([I[BII)V
 */
JNIEXPORT void JNICALL Java_framework_Thread_InferenceThread_YUVtoRGB
  (JNIEnv *, jobject, jintArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
