/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class framework_Manager_RecordManager */

#ifndef _Included_framework_Manager_RecordManager
#define _Included_framework_Manager_RecordManager
#ifdef __cplusplus
extern "C" {
#endif
#undef framework_Manager_RecordManager_MIN_PRIORITY
#define framework_Manager_RecordManager_MIN_PRIORITY 1L
#undef framework_Manager_RecordManager_NORM_PRIORITY
#define framework_Manager_RecordManager_NORM_PRIORITY 5L
#undef framework_Manager_RecordManager_MAX_PRIORITY
#define framework_Manager_RecordManager_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
